services:
  monogdb:
    image: mongo
    restart: always
    environment:
      - "MONGO_INITDB_ROOT_USERNAME: Arjun"
      - "MONGO_INITDB_ROOT_PASSWORD: Arjun@1234"
    container_name: mongo-server
    ports:
      - "27017"
    volumes:
      - db:/data/db
    networks:
    - ecommerce-network

  backend:
    depends_on:
      - mongodb
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-server
    restart: always
    ports:
      - "8000:8000"
    tty: true
    networks: 
      - ecommerce-network
    volumes:
      - ./backend/:/backend

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    restart: always
    ports:
      - "3000:3000"
    tty: true
    networks: 
      - ecommerce-network
    volumes:
      - ./frontend:/frontend

volumes:
  db:
networks:
  ecommerce-network: